const articles = [
    { img: "origins.svg", name: "Origins of Crypto", link: "/beginner-level/the-origins-of-crypto"},
    { img: "blockchain.svg", name: "Blockchain", link: "/beginner-level/blockchain-101" },
    { img: "bitcoin.svg", name: "Bitcoin", link: "/beginner-level/bitcoin" },
    { img: "mining.svg", name: "Mining", link: "/beginner-level/the-basics-of-mining" },
    { img: "consensus.svg", name: "Consensus Algorithms", link: "/beginner-level/cryptocurrency-consensus-algorithms" },
    { img: "litecoin.svg", name: "Litecoin", link: "/beginner-level/litecoin" },
    { img: "decentralisation.svg", name: "Decentralization as a concept", link: "/beginner-level/litecoin" },
    { img: "contracts.svg", name: "Smart Contracts & Dapps", link: "/beginner-level/decentralization-as-a-concept" },
    { img: "ethereum.svg", name: "Ethereum", link: "/beginner-level/ethereum" },
    { img: "funds.svg", name: "Crypto Wallets and Funds Safety", link: "/beginner-level/crypto-wallets-and-asset-security" },
    { img: "scaling.svg", name: "Scaling in Blockchain", link: "/beginner-level/blockchain-scaling" },
    { img: "eos.svg", name: "EOS", link: "/beginner-level/eos" },
    { img: "economy.svg", name: "Crypto Economy & Tokenomics", link: "/beginner-level/crypto-economy-and-tokenomics" },
    { img: "trading.svg", name: "Crypto Exchanges & Trading", link: "/beginner-level/crypto-economy-and-tokenomics" },
    { img: "usdt.svg", name: "USDT Tether", link: "/beginner-level/usdt-and-stablecoins" },
    { img: "cbdc.svg", name: "Crypto Legislation & CBDC", link: "/beginner-level/crypto-legislation"},
    { img: "finance.svg", name: "Blockchain in Traditional Finance", link: "/beginner-level/blockchain-in-traditional-finance" },
    { img: "ripple.svg", name: "Ripple", link: "/beginner-level/ripple" },
    {
      img: "review.svg",
      name: "Prominent Blockchain Projects & Platforms Review",
      link: "/beginner-level/prominent-blockchain-projects-and-platforms-review"
    },
    { img: "privacy.svg", name: "Privacy, Anonymity, & Data Protection",
    	link: "/beginner-level/privacy-anonymity-and-data-protection" },
    { img: "monero.svg", name: "Monero", link: "/beginner-level/monero" },
  ]